num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print("addition",num1+num2)
print("subtraction",num1-num2)
print("multiplication",num1*num2)
print("division",num1/num2)
print("remainder",num1%num2)

first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
print("Hello",first_name,last_name,"welcome to python programming")